//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillageApp.ImportCSVToSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPrice
    {
        public int Id { get; set; }
        public int ExchangeId { get; set; }
        public int StockSymbolId { get; set; }
        public System.DateTime Date { get; set; }
        public double StockPriceOpen { get; set; }
        public double StockPriceHigh { get; set; }
        public double StockPriceLow { get; set; }
        public double StockPriceClose { get; set; }
        public long StockVolume { get; set; }
        public double StockPriceAdjClose { get; set; }
    
        public virtual Exchanx Exchanx { get; set; }
        public virtual StockSymbol StockSymbol { get; set; }
    }
}
